sonar.organization=octavio200433
sonar.projectKey=Octavio200433_TP-agilesG1

# Rutas del proyecto
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Indicarle a SonarQube que solo evalúe la cobertura en el dominio
sonar.coverage.exclusions=src/ui/**, main.ts, vite.config.ts, vitest.config.ts, playwright.config.ts, tests/**, features/**